ControleDeContatos/Controllers/AlterarSenhaController.cs
using ControleDeContatos.Helper;
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController (IUsuarioRepositorio usuarioRepositorio, ISessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
            
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoUsuario();
                alterarSenhaModel.Id = usuarioLogado.Id;

                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso!";
                    return View("Index", alterarSenhaModel);
                }

                return View("Index", alterarSenhaModel);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = $"Não foi possível alterar sua senha, tente novamente!, erro: {ex.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

ControleDeContatos/Views/AlterarSenha/Index.cshtml
@using ControleDeContatos.Enums;
@model AlterarSenhaModel


@{
    ViewData["Title"] = "Alterar senha do usuário";

}

<div class="text-center">

    <h1 class="display-4">Alterar senha do usuário</h1>

    <div>

        @if (TempData["MensagemSucesso"] != null)
        {
            <div class="alert alert-success" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
                @TempData["MensagemSucesso"]
            </div>
        }

        @if (TempData["MensagemErro"] != null)
        {
            <div class="alert alert-danger" role="alert">
                <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
                @TempData["MensagemErro"]
            </div>
        }

        <form asp-controller="AlterarSenha" asp-action="Alterar" method="post">

            <div class="mb-3">
                <label for="senhaAtual" class="form-label">Senha atual</label>
                <input type="password" asp-for="SenhaAtual" class="form-control">
                @Html.ValidationMessageFor(x => x.SenhaAtual)
            </div>

            <div class="mb-3">
                <label for="novaSenha" class="form-label">Nova senha</label>
                <input type="password" asp-for="NovaSenha" class="form-control">
                @Html.ValidationMessageFor(x => x.NovaSenha)
            </div>

            <div class="mb-3">
                <label for="confirmar" class="form-label">Confirmar nova senha</label>
                <input type="password" asp-for="ConfirmarNovaSenha" class="form-control">
                @Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
            </div>

            <button type="submit" class="btn btn-primary btn-block">Alterar</button>
            <a class="btn btn-secondary btn-block" asp-controller="Home" asp-action="Index" role="button">Voltar</a>
        </form>
    </div>
</div>